Movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.ms,name='ms'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.addmovie,name="addmovie"),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movieapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='Gallery')
    def __str__(self):
        return self.name

movieapp/forms.py
# updating movie details
from django import forms
from .models import movies
class form_movie(forms.ModelForm):
    class Meta:
        model=movies
        fields=['name','desc','year','img']

movieapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import movies
from .forms import form_movie

# Create your views here.
def ms(request):
    movie=movies.objects.all()
    context={'movie_list':movie}
    return render(request,"index.html",context)
def detail(request,movie_id):
    m=movies.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':m})
def addmovie(request):
    if request.method=='POST':
        n=request.POST.get('name')
        d=request.POST.get('desc')
        y=request.POST.get('year')#fetching
        i=request.FILES['img']
        m=movies(name=n,desc=d,year=y,img=i) # add to database first one is the db feild name & second is the variable name
        m.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    mov=movies.objects.get(id=id)
    form=form_movie(request.POST or None,request.FILES,instance=mov)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render (request,'edit.html',{'f':form,'m':mov})
def delete(request,id):
    if request.method=='POST':
        mov=movies.objects.get(id=id)
        mov.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<h1 style="text-align: center;">Add Movies</h1>
<form method="POST" enctype="multipart/form-data" style="text-align: center;" > <!--enctype used for adding image file-->
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <input type="text" name="desc" placeholder="Enter movie description"><br>
    <input type="text" name="year" placeholder="Enter movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}  

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>index</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <!-- <link rel="icon" href="data:,"> -->
    </head>
    <body>
        <!-- for setting navbar -->  
        <!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'movieapp:ms' %}">
      Movie Store
    </a>
    <a class="navbar-brand" href="{% url 'movieapp:addmovie' %}">Add Movie</a>

  </nav>
  {% block body %}
  {% endblock %}
  </body>
    </body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <br>
        <p class="para">Are u sure want to delete this movie?</p>
                <button type="submit" class="btn btn-danger">confirm </button>
</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="250"><br>
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h4>{{movie.desc}}</h4>
            </h6>{{movie.year}}</h6>
            <a class="btn btn-success" href="{% url 'movieapp:update' movie.id %}">Update</a><!--update button-->
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a><!--delete button-->
        </div>
     </div>
</div>

{% endblock %}

templates/edit.html
<!-- Editing page -->
{% extends 'base.html' %}
{% block body %}
<br>
<h3>Update Movie Details</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{f.as_p}}
        <button type="submit" class="btn btn-success">confirm </button>
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
        <div class="row">
                {% for i in movie_list %}
                <div class="col-md-4">
                        <!-- bootstrap card code --> 
                        <div class="card" style="width: 18rem;">
                                <img src="{{i.img.url}}" class="card-img-top" alt="..." height="250px">
                                <div class="card-body">
                                  <h5 class="card-title">{{i.name}}</h5>
                                  <!-- <p class="card-text">{{i.desc}}</p> -->
                                  <a class="btn btn-info" href="{% url 'movieapp:detail' i.id %}" >Details</a> <!--a href creating link,detail is the name inside of def -->
                                </div>
                              </div>
                </div>
                {% endfor %}
        </div>
</div>
               
     
{% endblock %}